FROM internetsystemsconsortium/bind9:9.18

# Install iptables
RUN apk add --no-cache iptables

# Tűzfal script másolás
COPY firewall_settings/bind9_firewall.sh /firewall.sh

# Futtathatóvá tétel
RUN chmod +x /firewall.sh

# Indítás
ENTRYPOINT ["/bin/sh", "-c", "/firewall.sh && /usr/sbin/named -g -c /etc/bind/named.conf -u bind"]